steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/data-archeologist-ui', '-f', 'frontend/Dockerfile.frontend', './frontend']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/data-archeologist-ui']

images:
  - 'gcr.io/$PROJECT_ID/data-archeologist-ui'
